# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'X' do
    pod 'ParseUI'
    pod 'Parse'
    pod 'BMYCircularProgressPullToRefresh'
    pod 'SlackTextViewController'
    pod 'OpenSans'
end

target 'XTests' do

end

